// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type FederationToken struct {
	ID                int64          `json:"id"`
	Token             string         `json:"token"`
	OriginInstanceUrl string         `json:"origin_instance_url"`
	OriginShareToken  string         `json:"origin_share_token"`
	LocalUserID       int64          `json:"local_user_id"`
	ResourceType      string         `json:"resource_type"`
	ResourceID        int64          `json:"resource_id"`
	RemoteUserID      sql.NullInt64  `json:"remote_user_id"`
	RemoteUsername    sql.NullString `json:"remote_username"`
	ExpiresAt         sql.NullTime   `json:"expires_at"`
	LastUsedAt        sql.NullTime   `json:"last_used_at"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
}

type Folder struct {
	ID          int64         `json:"id"`
	UserID      int64         `json:"user_id"`
	ParentID    sql.NullInt64 `json:"parent_id"`
	Name        string        `json:"name"`
	FolderOrder int64         `json:"folder_order"`
	CreatedAt   sql.NullTime  `json:"created_at"`
	UpdatedAt   sql.NullTime  `json:"updated_at"`
}

type InstanceConfig struct {
	ID                int64        `json:"id"`
	InstanceUrl       string       `json:"instance_url"`
	InstanceName      string       `json:"instance_name"`
	AllowFederation   bool         `json:"allow_federation"`
	AllowPublicShares bool         `json:"allow_public_shares"`
	CreatedAt         sql.NullTime `json:"created_at"`
	UpdatedAt         sql.NullTime `json:"updated_at"`
}

type InstanceSetting struct {
	ID                   int64        `json:"id"`
	Name                 string       `json:"name"`
	CreatedAt            sql.NullTime `json:"created_at"`
	UpdatedAt            sql.NullTime `json:"updated_at"`
	SessionInvalidatedAt sql.NullTime `json:"session_invalidated_at"`
}

type InviteToken struct {
	ID        int64         `json:"id"`
	TokenHash string        `json:"token_hash"`
	TokenType string        `json:"token_type"`
	UserID    sql.NullInt64 `json:"user_id"`
	CreatedBy int64         `json:"created_by"`
	Email     string        `json:"email"`
	Used      bool          `json:"used"`
	UsedAt    sql.NullTime  `json:"used_at"`
	CreatedAt sql.NullTime  `json:"created_at"`
	ExpiresAt time.Time     `json:"expires_at"`
}

type Note struct {
	ID         int64         `json:"id"`
	UserID     int64         `json:"user_id"`
	TrackID    sql.NullInt64 `json:"track_id"`
	ProjectID  sql.NullInt64 `json:"project_id"`
	Content    string        `json:"content"`
	AuthorName string        `json:"author_name"`
	CreatedAt  sql.NullTime  `json:"created_at"`
	UpdatedAt  sql.NullTime  `json:"updated_at"`
}

type Project struct {
	ID                      int64          `json:"id"`
	UserID                  int64          `json:"user_id"`
	Name                    string         `json:"name"`
	Description             sql.NullString `json:"description"`
	QualityOverride         sql.NullString `json:"quality_override"`
	CreatedAt               sql.NullTime   `json:"created_at"`
	UpdatedAt               sql.NullTime   `json:"updated_at"`
	PublicID                string         `json:"public_id"`
	CoverArtPath            sql.NullString `json:"cover_art_path"`
	CoverArtMime            sql.NullString `json:"cover_art_mime"`
	CoverArtUpdatedAt       sql.NullTime   `json:"cover_art_updated_at"`
	AuthorOverride          sql.NullString `json:"author_override"`
	FolderID                sql.NullInt64  `json:"folder_id"`
	FolderAddedAt           sql.NullTime   `json:"folder_added_at"`
	Notes                   sql.NullString `json:"notes"`
	NotesAuthorName         sql.NullString `json:"notes_author_name"`
	NotesUpdatedAt          sql.NullTime   `json:"notes_updated_at"`
	VisibilityStatus        string         `json:"visibility_status"`
	AllowEditing            bool           `json:"allow_editing"`
	AllowDownloads          bool           `json:"allow_downloads"`
	PasswordHash            sql.NullString `json:"password_hash"`
	OriginInstanceUrl       sql.NullString `json:"origin_instance_url"`
	SharedWithInstanceUsers sql.NullBool   `json:"shared_with_instance_users"`
	CustomOrder             int64          `json:"custom_order"`
	CoverProcessed          sql.NullBool   `json:"cover_processed"`
}

type ProjectShareToken struct {
	ID                 int64          `json:"id"`
	Token              string         `json:"token"`
	UserID             int64          `json:"user_id"`
	ProjectID          int64          `json:"project_id"`
	ExpiresAt          sql.NullTime   `json:"expires_at"`
	MaxAccessCount     sql.NullInt64  `json:"max_access_count"`
	CurrentAccessCount sql.NullInt64  `json:"current_access_count"`
	AllowEditing       bool           `json:"allow_editing"`
	AllowDownloads     bool           `json:"allow_downloads"`
	PasswordHash       sql.NullString `json:"password_hash"`
	VisibilityType     string         `json:"visibility_type"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
}

type RefreshToken struct {
	ID         int64          `json:"id"`
	UserID     int64          `json:"user_id"`
	TokenHash  string         `json:"token_hash"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	ExpiresAt  time.Time      `json:"expires_at"`
	RevokedAt  sql.NullTime   `json:"revoked_at"`
	LastUsedAt sql.NullTime   `json:"last_used_at"`
	UserAgent  sql.NullString `json:"user_agent"`
	Ip         sql.NullString `json:"ip"`
}

type RemoteTrack struct {
	ID                int64          `json:"id"`
	LocalUserID       int64          `json:"local_user_id"`
	LocalProjectID    int64          `json:"local_project_id"`
	RemoteInstanceUrl string         `json:"remote_instance_url"`
	RemoteTrackID     int64          `json:"remote_track_id"`
	ShareToken        string         `json:"share_token"`
	Title             string         `json:"title"`
	Artist            sql.NullString `json:"artist"`
	Album             sql.NullString `json:"album"`
	CachedMetadata    sql.NullString `json:"cached_metadata"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
}

type ShareAccess struct {
	ID                int64          `json:"id"`
	ShareType         string         `json:"share_type"`
	ShareTokenID      int64          `json:"share_token_id"`
	UserID            int64          `json:"user_id"`
	UserInstanceUrl   sql.NullString `json:"user_instance_url"`
	FederationTokenID sql.NullInt64  `json:"federation_token_id"`
	AcceptedAt        sql.NullTime   `json:"accepted_at"`
	LastAccessedAt    sql.NullTime   `json:"last_accessed_at"`
	AccessCount       sql.NullInt64  `json:"access_count"`
	CanEdit           bool           `json:"can_edit"`
	CanDownload       bool           `json:"can_download"`
}

type ShareToken struct {
	ID                 int64          `json:"id"`
	Token              string         `json:"token"`
	UserID             int64          `json:"user_id"`
	TrackID            int64          `json:"track_id"`
	VersionID          sql.NullInt64  `json:"version_id"`
	ExpiresAt          sql.NullTime   `json:"expires_at"`
	MaxAccessCount     sql.NullInt64  `json:"max_access_count"`
	CurrentAccessCount sql.NullInt64  `json:"current_access_count"`
	AllowEditing       bool           `json:"allow_editing"`
	AllowDownloads     bool           `json:"allow_downloads"`
	PasswordHash       sql.NullString `json:"password_hash"`
	VisibilityType     string         `json:"visibility_type"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
}

type Track struct {
	ID                      int64          `json:"id"`
	UserID                  int64          `json:"user_id"`
	ProjectID               int64          `json:"project_id"`
	Title                   string         `json:"title"`
	Artist                  sql.NullString `json:"artist"`
	Album                   sql.NullString `json:"album"`
	ActiveVersionID         sql.NullInt64  `json:"active_version_id"`
	CreatedAt               sql.NullTime   `json:"created_at"`
	UpdatedAt               sql.NullTime   `json:"updated_at"`
	TrackOrder              int64          `json:"track_order"`
	Key                     sql.NullString `json:"key"`
	Bpm                     sql.NullInt64  `json:"bpm"`
	PublicID                string         `json:"public_id"`
	Notes                   sql.NullString `json:"notes"`
	NotesAuthorName         sql.NullString `json:"notes_author_name"`
	NotesUpdatedAt          sql.NullTime   `json:"notes_updated_at"`
	VisibilityStatus        string         `json:"visibility_status"`
	AllowEditing            bool           `json:"allow_editing"`
	AllowDownloads          bool           `json:"allow_downloads"`
	PasswordHash            sql.NullString `json:"password_hash"`
	OriginInstanceUrl       sql.NullString `json:"origin_instance_url"`
	SharedWithInstanceUsers sql.NullBool   `json:"shared_with_instance_users"`
}

type TrackFile struct {
	ID                int64          `json:"id"`
	VersionID         int64          `json:"version_id"`
	Quality           string         `json:"quality"`
	FilePath          string         `json:"file_path"`
	FileSize          int64          `json:"file_size"`
	Format            string         `json:"format"`
	Bitrate           sql.NullInt64  `json:"bitrate"`
	ContentHash       sql.NullString `json:"content_hash"`
	TranscodingStatus sql.NullString `json:"transcoding_status"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	Waveform          sql.NullString `json:"waveform"`
	OriginalFilename  sql.NullString `json:"original_filename"`
}

type TrackVersion struct {
	ID              int64           `json:"id"`
	TrackID         int64           `json:"track_id"`
	VersionName     string          `json:"version_name"`
	Notes           sql.NullString  `json:"notes"`
	DurationSeconds sql.NullFloat64 `json:"duration_seconds"`
	VersionOrder    int64           `json:"version_order"`
	CreatedAt       sql.NullTime    `json:"created_at"`
	UpdatedAt       sql.NullTime    `json:"updated_at"`
}

type User struct {
	ID                   int64        `json:"id"`
	Username             string       `json:"username"`
	Email                string       `json:"email"`
	PasswordHash         string       `json:"password_hash"`
	CreatedAt            sql.NullTime `json:"created_at"`
	UpdatedAt            sql.NullTime `json:"updated_at"`
	IsAdmin              bool         `json:"is_admin"`
	IsOwner              bool         `json:"is_owner"`
	SessionInvalidatedAt sql.NullTime `json:"session_invalidated_at"`
}

type UserPreference struct {
	UserID              int64          `json:"user_id"`
	DefaultQuality      string         `json:"default_quality"`
	CreatedAt           sql.NullTime   `json:"created_at"`
	UpdatedAt           sql.NullTime   `json:"updated_at"`
	DiscColors          sql.NullString `json:"disc_colors"`
	ColorSpread         sql.NullInt64  `json:"color_spread"`
	GradientSpread      sql.NullInt64  `json:"gradient_spread"`
	TrackInsertPosition string         `json:"track_insert_position"`
	ColorShiftRotation  sql.NullInt64  `json:"color_shift_rotation"`
}

type UserProjectShare struct {
	ID          int64        `json:"id"`
	ProjectID   int64        `json:"project_id"`
	SharedBy    int64        `json:"shared_by"`
	SharedTo    int64        `json:"shared_to"`
	CanEdit     bool         `json:"can_edit"`
	CanDownload bool         `json:"can_download"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type UserSharedProjectOrganization struct {
	ID          int64         `json:"id"`
	UserID      int64         `json:"user_id"`
	ProjectID   int64         `json:"project_id"`
	FolderID    sql.NullInt64 `json:"folder_id"`
	CustomOrder int64         `json:"custom_order"`
	CreatedAt   sql.NullTime  `json:"created_at"`
	UpdatedAt   sql.NullTime  `json:"updated_at"`
}

type UserSharedTrackOrganization struct {
	ID          int64         `json:"id"`
	UserID      int64         `json:"user_id"`
	TrackID     int64         `json:"track_id"`
	FolderID    sql.NullInt64 `json:"folder_id"`
	CustomOrder int64         `json:"custom_order"`
	CreatedAt   sql.NullTime  `json:"created_at"`
	UpdatedAt   sql.NullTime  `json:"updated_at"`
}

type UserTrackShare struct {
	ID          int64        `json:"id"`
	TrackID     int64        `json:"track_id"`
	SharedBy    int64        `json:"shared_by"`
	SharedTo    int64        `json:"shared_to"`
	CanEdit     bool         `json:"can_edit"`
	CanDownload bool         `json:"can_download"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type ListenEvent struct {
	ID               int64         `json:"id"`
	EventType        string        `json:"event_type"`
	TrackOwnerID     int64         `json:"track_owner_id"`
	TrackID          sql.NullInt64 `json:"track_id"`
	TrackTitle       string        `json:"track_title"`
	PlayedByUserID   sql.NullInt64 `json:"played_by_user_id"`
	PlayedByUsername string        `json:"played_by_username"`
	PlayedAt         sql.NullTime  `json:"played_at"`
	Read             bool          `json:"read"`
}

type WebsocketSession struct {
	ID              int64          `json:"id"`
	SessionID       string         `json:"session_id"`
	UserID          int64          `json:"user_id"`
	UserInstanceUrl sql.NullString `json:"user_instance_url"`
	ResourceType    string         `json:"resource_type"`
	ResourceID      string         `json:"resource_id"`
	ConnectedAt     sql.NullTime   `json:"connected_at"`
	LastHeartbeatAt sql.NullTime   `json:"last_heartbeat_at"`
}
