// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CheckFolderExists(ctx context.Context, arg CheckFolderExistsParams) (int64, error)
	ClearAllTracksAnalysis(ctx context.Context) error
	ClearProjectCover(ctx context.Context, id int64) (Project, error)
	ClearTrackAnalysis(ctx context.Context, id int64) error
	CountProjectsInFolder(ctx context.Context, folderID sql.NullInt64) (int64, error)
	CountSubfoldersInFolder(ctx context.Context, parentID sql.NullInt64) (int64, error)
	CountTrackVersions(ctx context.Context, trackID int64) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateListenEvent(ctx context.Context, arg CreateListenEventParams) (ListenEvent, error)
	DeleteListenEvent(ctx context.Context, arg DeleteListenEventParams) error
	GetListenEvents(ctx context.Context, trackOwnerID int64) ([]ListenEvent, error)
	GetProjectStreamStats(ctx context.Context, projectID int64) ([]GetProjectStreamStatsRow, error)
	GetTrackStats(ctx context.Context, trackID int64) (GetTrackStatsRow, error)
	GetUnreadListenEventsCount(ctx context.Context, trackOwnerID int64) (int64, error)
	MarkAllListenEventsRead(ctx context.Context, trackOwnerID int64) error
	RecentListenEventExists(ctx context.Context, arg RecentListenEventExistsParams) (int64, error)
	// FEDERATION TOKENS
	CreateFederationToken(ctx context.Context, arg CreateFederationTokenParams) (FederationToken, error)
	CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error)
	CreateInviteToken(ctx context.Context, arg CreateInviteTokenParams) (InviteToken, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateProjectNote(ctx context.Context, arg CreateProjectNoteParams) (Note, error)
	// PROJECT SHARE TOKENS
	CreateProjectShareToken(ctx context.Context, arg CreateProjectShareTokenParams) (ProjectShareToken, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateRemoteTrack(ctx context.Context, arg CreateRemoteTrackParams) (RemoteTrack, error)
	CreateResetToken(ctx context.Context, arg CreateResetTokenParams) (InviteToken, error)
	// SHARE ACCESS
	CreateShareAccess(ctx context.Context, arg CreateShareAccessParams) (ShareAccess, error)
	// TRACK SHARE TOKENS
	CreateShareToken(ctx context.Context, arg CreateShareTokenParams) (ShareToken, error)
	CreateSharedProjectOrganization(ctx context.Context, arg CreateSharedProjectOrganizationParams) (UserSharedProjectOrganization, error)
	CreateSharedTrackOrganization(ctx context.Context, arg CreateSharedTrackOrganizationParams) (UserSharedTrackOrganization, error)
	CreateTrack(ctx context.Context, arg CreateTrackParams) (Track, error)
	CreateTrackFile(ctx context.Context, arg CreateTrackFileParams) (TrackFile, error)
	CreateTrackNote(ctx context.Context, arg CreateTrackNoteParams) (Note, error)
	CreateTrackVersion(ctx context.Context, arg CreateTrackVersionParams) (TrackVersion, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserPreferences(ctx context.Context, arg CreateUserPreferencesParams) error
	// USER-TO-USER SHARING (SAME INSTANCE)
	CreateUserProjectShare(ctx context.Context, arg CreateUserProjectShareParams) (UserProjectShare, error)
	CreateUserTrackShare(ctx context.Context, arg CreateUserTrackShareParams) (UserTrackShare, error)
	// WEBSOCKET SESSIONS
	CreateWebSocketSession(ctx context.Context, arg CreateWebSocketSessionParams) (WebsocketSession, error)
	DeleteAllSharedProjectOrganizationsInFolder(ctx context.Context, arg DeleteAllSharedProjectOrganizationsInFolderParams) error
	DeleteAllSharedTrackOrganizationsInFolder(ctx context.Context, arg DeleteAllSharedTrackOrganizationsInFolderParams) error
	DeleteExpiredFederationTokens(ctx context.Context) error
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteExpiredTokens(ctx context.Context) error
	DeleteFederationToken(ctx context.Context, arg DeleteFederationTokenParams) error
	DeleteFederationTokenByToken(ctx context.Context, token string) error
	DeleteFolder(ctx context.Context, arg DeleteFolderParams) error
	DeleteFolderByID(ctx context.Context, id int64) error
	DeleteNote(ctx context.Context, arg DeleteNoteParams) error
	DeleteProject(ctx context.Context, arg DeleteProjectParams) error
	DeleteProjectShareToken(ctx context.Context, arg DeleteProjectShareTokenParams) error
	DeleteProjectShareTokenByProject(ctx context.Context, arg DeleteProjectShareTokenByProjectParams) error
	DeleteRemoteTrack(ctx context.Context, arg DeleteRemoteTrackParams) error
	DeleteShareAccess(ctx context.Context, arg DeleteShareAccessParams) error
	DeleteShareAccessByShare(ctx context.Context, arg DeleteShareAccessByShareParams) error
	DeleteShareToken(ctx context.Context, arg DeleteShareTokenParams) error
	DeleteShareTokenByTrack(ctx context.Context, arg DeleteShareTokenByTrackParams) error
	DeleteSharedProjectOrganization(ctx context.Context, arg DeleteSharedProjectOrganizationParams) error
	DeleteSharedTrackOrganization(ctx context.Context, arg DeleteSharedTrackOrganizationParams) error
	DeleteStaleWebSocketSessions(ctx context.Context) error
	DeleteTrack(ctx context.Context, arg DeleteTrackParams) error
	DeleteTrackFile(ctx context.Context, id int64) error
	DeleteTrackFilesByVersion(ctx context.Context, versionID int64) error
	DeleteTrackVersion(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteUserByID(ctx context.Context, id int64) error
	DeleteUserProjectShare(ctx context.Context, arg DeleteUserProjectShareParams) error
	DeleteUserProjectShareByID(ctx context.Context, arg DeleteUserProjectShareByIDParams) error
	DeleteUserTrackShare(ctx context.Context, arg DeleteUserTrackShareParams) error
	DeleteUserTrackShareByID(ctx context.Context, arg DeleteUserTrackShareByIDParams) error
	DeleteUserTrackShareByShareID(ctx context.Context, id int64) error
	DeleteWebSocketSession(ctx context.Context, sessionID string) error
	FindFileByContentHash(ctx context.Context, contentHash sql.NullString) (TrackFile, error)
	GetCompletedTrackFile(ctx context.Context, arg GetCompletedTrackFileParams) (TrackFile, error)
	GetFederationToken(ctx context.Context, token string) (FederationToken, error)
	GetFederationTokenByID(ctx context.Context, id int64) (FederationToken, error)
	GetFolder(ctx context.Context, arg GetFolderParams) (Folder, error)
	GetFolderByID(ctx context.Context, id int64) (Folder, error)
	GetGlobalStorageStats(ctx context.Context) (GetGlobalStorageStatsRow, error)
	// INSTANCE CONFIGURATION
	GetInstanceConfig(ctx context.Context) (InstanceConfig, error)
	GetInstanceSettings(ctx context.Context) (InstanceSetting, error)
	GetInviteTokenByToken(ctx context.Context, tokenHash string) (InviteToken, error)
	// Get the maximum custom_order across all item types at root level
	GetMaxOrderAtRoot(ctx context.Context, userID int64) (interface{}, error)
	// Get the maximum custom_order across all item types in a folder
	// This ensures new items are appended after existing projects, tracks, and subfolders
	GetMaxOrderInFolder(ctx context.Context, arg GetMaxOrderInFolderParams) (interface{}, error)
	GetMaxProjectOrderAtRoot(ctx context.Context, arg GetMaxProjectOrderAtRootParams) (interface{}, error)
	GetMaxProjectOrderInFolder(ctx context.Context, arg GetMaxProjectOrderInFolderParams) (interface{}, error)
	GetMaxTrackOrderAtRoot(ctx context.Context, userID int64) (interface{}, error)
	GetMaxTrackOrderByProject(ctx context.Context, projectID int64) (interface{}, error)
	GetMaxTrackOrderInFolder(ctx context.Context, arg GetMaxTrackOrderInFolderParams) (interface{}, error)
	GetMaxVersionOrder(ctx context.Context, trackID int64) (interface{}, error)
	GetNotesByProject(ctx context.Context, projectID sql.NullInt64) ([]Note, error)
	GetNotesByTrack(ctx context.Context, trackID sql.NullInt64) ([]Note, error)
	GetProject(ctx context.Context, arg GetProjectParams) (Project, error)
	GetProjectByID(ctx context.Context, id int64) (Project, error)
	GetProjectByPublicID(ctx context.Context, arg GetProjectByPublicIDParams) (GetProjectByPublicIDRow, error)
	GetProjectByPublicIDNoFilter(ctx context.Context, publicID string) (GetProjectByPublicIDNoFilterRow, error)
	GetProjectShareToken(ctx context.Context, token string) (ProjectShareToken, error)
	GetProjectShareTokenByID(ctx context.Context, arg GetProjectShareTokenByIDParams) (ProjectShareToken, error)
	GetProjectShareTokenByProject(ctx context.Context, arg GetProjectShareTokenByProjectParams) (ProjectShareToken, error)
	GetPublicProjects(ctx context.Context, arg GetPublicProjectsParams) ([]Project, error)
	GetPublicTracks(ctx context.Context, arg GetPublicTracksParams) ([]Track, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRemoteTrack(ctx context.Context, arg GetRemoteTrackParams) (RemoteTrack, error)
	GetSessionInvalidatedAt(ctx context.Context) (sql.NullTime, error)
	GetShareAccess(ctx context.Context, arg GetShareAccessParams) (ShareAccess, error)
	GetShareToken(ctx context.Context, token string) (ShareToken, error)
	GetShareTokenByID(ctx context.Context, arg GetShareTokenByIDParams) (ShareToken, error)
	GetShareTokenByTrack(ctx context.Context, arg GetShareTokenByTrackParams) (ShareToken, error)
	GetStorageStatsByUser(ctx context.Context, userID int64) (GetStorageStatsByUserRow, error)
	GetTokensByUser(ctx context.Context, arg GetTokensByUserParams) ([]InviteToken, error)
	GetTrack(ctx context.Context, arg GetTrackParams) (Track, error)
	GetTrackByID(ctx context.Context, id int64) (Track, error)
	GetTrackByPublicID(ctx context.Context, arg GetTrackByPublicIDParams) (Track, error)
	GetTrackByPublicIDNoFilter(ctx context.Context, publicID string) (Track, error)
	GetTrackFile(ctx context.Context, arg GetTrackFileParams) (TrackFile, error)
	GetTrackVersion(ctx context.Context, id int64) (TrackVersion, error)
	GetTrackVersionWithOwnership(ctx context.Context, id int64) (GetTrackVersionWithOwnershipRow, error)
	GetTrackWithDetails(ctx context.Context, arg GetTrackWithDetailsParams) (GetTrackWithDetailsRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserInviteTokens(ctx context.Context, createdBy int64) ([]InviteToken, error)
	GetUserNoteForProject(ctx context.Context, arg GetUserNoteForProjectParams) (Note, error)
	GetUserNoteForTrack(ctx context.Context, arg GetUserNoteForTrackParams) (Note, error)
	GetUserPreferences(ctx context.Context, userID int64) (UserPreference, error)
	GetUserProjectShare(ctx context.Context, arg GetUserProjectShareParams) (UserProjectShare, error)
	GetUserSessionInvalidatedAt(ctx context.Context, id int64) (sql.NullTime, error)
	GetUserSharedProjectOrganization(ctx context.Context, arg GetUserSharedProjectOrganizationParams) (UserSharedProjectOrganization, error)
	GetUserSharedTrackOrganization(ctx context.Context, arg GetUserSharedTrackOrganizationParams) (UserSharedTrackOrganization, error)
	GetUserTrackShare(ctx context.Context, arg GetUserTrackShareParams) (UserTrackShare, error)
	GetUserTrackShareByID(ctx context.Context, id int64) (UserTrackShare, error)
	GetWebSocketSession(ctx context.Context, sessionID string) (WebsocketSession, error)
	IncrementTrackOrdersByProject(ctx context.Context, projectID int64) error
	IncrementAccessCount(ctx context.Context, id int64) error
	IncrementProjectAccessCount(ctx context.Context, id int64) error
	InvalidateSessions(ctx context.Context) error
	ListAllFoldersByUser(ctx context.Context, userID int64) ([]Folder, error)
	ListAllTrackFiles(ctx context.Context) ([]TrackFile, error)
	ListAllUsers(ctx context.Context) ([]User, error)
	ListFederationTokensByOrigin(ctx context.Context, arg ListFederationTokensByOriginParams) ([]FederationToken, error)
	ListFederationTokensByUser(ctx context.Context, localUserID int64) ([]FederationToken, error)
	ListFoldersByParent(ctx context.Context, arg ListFoldersByParentParams) ([]Folder, error)
	ListFoldersByUser(ctx context.Context, userID int64) ([]Folder, error)
	ListPlainTracksByProject(ctx context.Context, arg ListPlainTracksByProjectParams) ([]Track, error)
	ListProjectShareTokensByProject(ctx context.Context, projectID int64) ([]ProjectShareToken, error)
	ListProjectShareTokensByUser(ctx context.Context, userID int64) ([]ProjectShareToken, error)
	ListProjectShareTokensWithProjectInfo(ctx context.Context, userID int64) ([]ListProjectShareTokensWithProjectInfoRow, error)
	ListProjectsByUser(ctx context.Context, userID int64) ([]ListProjectsByUserRow, error)
	ListProjectsInFolder(ctx context.Context, arg ListProjectsInFolderParams) ([]ListProjectsInFolderRow, error)
	ListProjectsSharedByUser(ctx context.Context, sharedBy int64) ([]UserProjectShare, error)
	ListProjectsSharedWithUser(ctx context.Context, sharedTo int64) ([]Project, error)
	ListRemoteTracksByProject(ctx context.Context, arg ListRemoteTracksByProjectParams) ([]RemoteTrack, error)
	ListRemoteTracksByUser(ctx context.Context, localUserID int64) ([]RemoteTrack, error)
	ListRootProjects(ctx context.Context, userID int64) ([]ListRootProjectsRow, error)
	ListRootProjectsWithCustomOrder(ctx context.Context, userID int64) ([]Project, error)
	ListShareAccessByShare(ctx context.Context, arg ListShareAccessByShareParams) ([]ShareAccess, error)
	ListShareAccessByUser(ctx context.Context, userID int64) ([]ShareAccess, error)
	ListShareTokensByTrack(ctx context.Context, trackID int64) ([]ShareToken, error)
	ListShareTokensByUser(ctx context.Context, userID int64) ([]ShareToken, error)
	ListShareTokensWithTrackInfo(ctx context.Context, userID int64) ([]ListShareTokensWithTrackInfoRow, error)
	ListSharedProjectOrganizationsAtRoot(ctx context.Context, userID int64) ([]UserSharedProjectOrganization, error)
	ListSharedProjectOrganizationsInFolder(ctx context.Context, arg ListSharedProjectOrganizationsInFolderParams) ([]UserSharedProjectOrganization, error)
	ListSharedTrackOrganizationsAtRoot(ctx context.Context, userID int64) ([]UserSharedTrackOrganization, error)
	ListSharedTrackOrganizationsInFolder(ctx context.Context, arg ListSharedTrackOrganizationsInFolderParams) ([]UserSharedTrackOrganization, error)
	ListTrackFilesByVersion(ctx context.Context, versionID int64) ([]TrackFile, error)
	ListTrackVersions(ctx context.Context, trackID int64) ([]TrackVersion, error)
	ListTrackVersionsWithMetadata(ctx context.Context, trackID int64) ([]ListTrackVersionsWithMetadataRow, error)
	ListTracksByProject(ctx context.Context, arg ListTracksByProjectParams) ([]ListTracksByProjectRow, error)
	ListTracksByProjectID(ctx context.Context, projectID int64) ([]Track, error)
	ListTracksByUser(ctx context.Context, userID int64) ([]ListTracksByUserRow, error)
	ListTracksSharedByUser(ctx context.Context, sharedBy int64) ([]UserTrackShare, error)
	ListTracksSharedWithUser(ctx context.Context, sharedTo int64) ([]Track, error)
	ListTracksWithDetailsByProjectID(ctx context.Context, projectID int64) ([]ListTracksWithDetailsByProjectIDRow, error)
	ListTracksWithoutAnalysis(ctx context.Context) ([]ListTracksWithoutAnalysisRow, error)
	ListTracksWithoutBPM(ctx context.Context) ([]ListTracksWithoutBPMRow, error)
	ListUnprocessedCovers(ctx context.Context) ([]Project, error)
	ListUserSharedProjectOrganizations(ctx context.Context, userID int64) ([]UserSharedProjectOrganization, error)
	ListUserSharedTrackOrganizations(ctx context.Context, userID int64) ([]UserSharedTrackOrganization, error)
	ListUsersProjectIsSharedWith(ctx context.Context, projectID int64) ([]UserProjectShare, error)
	ListUsersTrackIsSharedWith(ctx context.Context, trackID int64) ([]UserTrackShare, error)
	ListWebSocketSessionsByResource(ctx context.Context, arg ListWebSocketSessionsByResourceParams) ([]WebsocketSession, error)
	MarkCoverProcessed(ctx context.Context, id int64) error
	MarkTokenAsUsed(ctx context.Context, id int64) (InviteToken, error)
	RevokeRefreshToken(ctx context.Context, id int64) error
	RevokeRefreshTokensByUser(ctx context.Context, userID int64) error
	SearchTracksAccessibleByUser(ctx context.Context, arg SearchTracksAccessibleByUserParams) ([]SearchTracksAccessibleByUserRow, error)
	SetActiveVersion(ctx context.Context, arg SetActiveVersionParams) error
	UpdateFederationTokenLastUsed(ctx context.Context, id int64) error
	UpdateFolder(ctx context.Context, arg UpdateFolderParams) (Folder, error)
	UpdateFolderName(ctx context.Context, arg UpdateFolderNameParams) (Folder, error)
	UpdateFolderOrder(ctx context.Context, arg UpdateFolderOrderParams) error
	UpdateFolderParent(ctx context.Context, arg UpdateFolderParentParams) (Folder, error)
	UpdateInstanceConfig(ctx context.Context, arg UpdateInstanceConfigParams) (InstanceConfig, error)
	UpdateInstanceName(ctx context.Context, name string) (InstanceSetting, error)
	UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateProjectCover(ctx context.Context, arg UpdateProjectCoverParams) (Project, error)
	UpdateProjectCustomOrder(ctx context.Context, arg UpdateProjectCustomOrderParams) (Project, error)
	UpdateProjectFolder(ctx context.Context, arg UpdateProjectFolderParams) (Project, error)
	UpdateProjectFolderWithTimestamp(ctx context.Context, arg UpdateProjectFolderWithTimestampParams) (Project, error)
	UpdateProjectNotes(ctx context.Context, arg UpdateProjectNotesParams) (Project, error)
	UpdateProjectShareToken(ctx context.Context, arg UpdateProjectShareTokenParams) (ProjectShareToken, error)
	UpdateProjectVisibility(ctx context.Context, arg UpdateProjectVisibilityParams) (Project, error)
	UpdateProjectVisibilityByPublicID(ctx context.Context, arg UpdateProjectVisibilityByPublicIDParams) (Project, error)
	UpdateRefreshTokenLastUsed(ctx context.Context, id int64) error
	UpdateRemoteTrack(ctx context.Context, arg UpdateRemoteTrackParams) (RemoteTrack, error)
	UpdateShareAccessLastAccessed(ctx context.Context, id int64) error
	UpdateShareToken(ctx context.Context, arg UpdateShareTokenParams) (ShareToken, error)
	UpdateSharedProjectOrganization(ctx context.Context, arg UpdateSharedProjectOrganizationParams) (UserSharedProjectOrganization, error)
	UpdateSharedTrackOrganization(ctx context.Context, arg UpdateSharedTrackOrganizationParams) (UserSharedTrackOrganization, error)
	UpdateTrack(ctx context.Context, arg UpdateTrackParams) (Track, error)
	UpdateTrackAnalysis(ctx context.Context, arg UpdateTrackAnalysisParams) error
	UpdateTrackBPM(ctx context.Context, arg UpdateTrackBPMParams) error
	UpdateTrackFileSize(ctx context.Context, arg UpdateTrackFileSizeParams) error
	UpdateTrackNotes(ctx context.Context, arg UpdateTrackNotesParams) (Track, error)
	UpdateTrackOrder(ctx context.Context, arg UpdateTrackOrderParams) error
	UpdateTrackVersion(ctx context.Context, arg UpdateTrackVersionParams) (TrackVersion, error)
	UpdateTrackVersionDuration(ctx context.Context, arg UpdateTrackVersionDurationParams) error
	// VISIBILITY STATUS OPERATIONS
	UpdateTrackVisibility(ctx context.Context, arg UpdateTrackVisibilityParams) (Track, error)
	UpdateTrackVisibilityByPublicID(ctx context.Context, arg UpdateTrackVisibilityByPublicIDParams) (Track, error)
	UpdateTrackVisibilityByPublicIDNoUserFilter(ctx context.Context, arg UpdateTrackVisibilityByPublicIDNoUserFilterParams) (Track, error)
	UpdateTranscodingStatus(ctx context.Context, arg UpdateTranscodingStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
	UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (UserPreference, error)
	UpdateUserProjectShare(ctx context.Context, arg UpdateUserProjectShareParams) (UserProjectShare, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
	UpdateUserSessionInvalidatedAt(ctx context.Context, id int64) error
	UpdateUserTrackShare(ctx context.Context, arg UpdateUserTrackShareParams) (UserTrackShare, error)
	UpdateUserTrackShareByID(ctx context.Context, arg UpdateUserTrackShareByIDParams) (UserTrackShare, error)
	UpdateUsername(ctx context.Context, arg UpdateUsernameParams) (User, error)
	UpdateWaveform(ctx context.Context, arg UpdateWaveformParams) error
	UpdateWebSocketHeartbeat(ctx context.Context, sessionID string) error
	UpsertInstanceSettings(ctx context.Context, name string) (InstanceSetting, error)
	UpsertProjectNote(ctx context.Context, arg UpsertProjectNoteParams) (Note, error)
	UpsertSharedProjectOrganization(ctx context.Context, arg UpsertSharedProjectOrganizationParams) (UserSharedProjectOrganization, error)
	UpsertSharedTrackOrganization(ctx context.Context, arg UpsertSharedTrackOrganizationParams) (UserSharedTrackOrganization, error)
	UpsertTrackNote(ctx context.Context, arg UpsertTrackNoteParams) (Note, error)
}

var _ Querier = (*Queries)(nil)
