// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stem_jobs.sql

package db

import (
	"context"
	"database/sql"
)

const createStemJob = `-- name: CreateStemJob :one
INSERT INTO stem_jobs (version_id, user_id, track_public_id, status)
VALUES (?, ?, ?, 'pending')
RETURNING id, version_id, user_id, track_public_id, status, error_message, created_at, updated_at
`

type CreateStemJobParams struct {
	VersionID     int64  `json:"version_id"`
	UserID        int64  `json:"user_id"`
	TrackPublicID string `json:"track_public_id"`
}

func (q *Queries) CreateStemJob(ctx context.Context, arg CreateStemJobParams) (StemJob, error) {
	row := q.db.QueryRowContext(ctx, createStemJob, arg.VersionID, arg.UserID, arg.TrackPublicID)
	var i StemJob
	err := row.Scan(
		&i.ID,
		&i.VersionID,
		&i.UserID,
		&i.TrackPublicID,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStemFilesByVersion = `-- name: DeleteStemFilesByVersion :exec
DELETE FROM track_files
WHERE version_id = ? AND quality LIKE 'stem_%'
`

func (q *Queries) DeleteStemFilesByVersion(ctx context.Context, versionID int64) error {
	_, err := q.db.ExecContext(ctx, deleteStemFilesByVersion, versionID)
	return err
}

const deleteStemJobsByVersion = `-- name: DeleteStemJobsByVersion :exec
DELETE FROM stem_jobs
WHERE version_id = ?
`

func (q *Queries) DeleteStemJobsByVersion(ctx context.Context, versionID int64) error {
	_, err := q.db.ExecContext(ctx, deleteStemJobsByVersion, versionID)
	return err
}

const getStemJob = `-- name: GetStemJob :one
SELECT id, version_id, user_id, track_public_id, status, error_message, created_at, updated_at FROM stem_jobs
WHERE id = ?
`

func (q *Queries) GetStemJob(ctx context.Context, id int64) (StemJob, error) {
	row := q.db.QueryRowContext(ctx, getStemJob, id)
	var i StemJob
	err := row.Scan(
		&i.ID,
		&i.VersionID,
		&i.UserID,
		&i.TrackPublicID,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStemJobByVersionID = `-- name: GetStemJobByVersionID :one
SELECT id, version_id, user_id, track_public_id, status, error_message, created_at, updated_at FROM stem_jobs
WHERE version_id = ?
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetStemJobByVersionID(ctx context.Context, versionID int64) (StemJob, error) {
	row := q.db.QueryRowContext(ctx, getStemJobByVersionID, versionID)
	var i StemJob
	err := row.Scan(
		&i.ID,
		&i.VersionID,
		&i.UserID,
		&i.TrackPublicID,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStemFilesByVersion = `-- name: ListStemFilesByVersion :many
SELECT id, version_id, quality, file_path, file_size, format, bitrate, content_hash, transcoding_status, created_at, waveform, original_filename FROM track_files
WHERE version_id = ? AND quality LIKE 'stem_%'
`

func (q *Queries) ListStemFilesByVersion(ctx context.Context, versionID int64) ([]TrackFile, error) {
	rows, err := q.db.QueryContext(ctx, listStemFilesByVersion, versionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrackFile{}
	for rows.Next() {
		var i TrackFile
		if err := rows.Scan(
			&i.ID,
			&i.VersionID,
			&i.Quality,
			&i.FilePath,
			&i.FileSize,
			&i.Format,
			&i.Bitrate,
			&i.ContentHash,
			&i.TranscodingStatus,
			&i.CreatedAt,
			&i.Waveform,
			&i.OriginalFilename,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStemJobError = `-- name: UpdateStemJobError :exec
UPDATE stem_jobs
SET status = 'failed', error_message = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateStemJobErrorParams struct {
	ErrorMessage sql.NullString `json:"error_message"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateStemJobError(ctx context.Context, arg UpdateStemJobErrorParams) error {
	_, err := q.db.ExecContext(ctx, updateStemJobError, arg.ErrorMessage, arg.ID)
	return err
}

const updateStemJobStatus = `-- name: UpdateStemJobStatus :exec
UPDATE stem_jobs
SET status = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateStemJobStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateStemJobStatus(ctx context.Context, arg UpdateStemJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateStemJobStatus, arg.Status, arg.ID)
	return err
}
