// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: track_files.sql

package db

import (
	"context"
	"database/sql"
)

const createTrackFile = `-- name: CreateTrackFile :one
INSERT INTO track_files (version_id, quality, file_path, file_size, format, bitrate, content_hash, transcoding_status, original_filename)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, version_id, quality, file_path, file_size, format, bitrate, content_hash, transcoding_status, created_at, waveform, original_filename
`

type CreateTrackFileParams struct {
	VersionID         int64          `json:"version_id"`
	Quality           string         `json:"quality"`
	FilePath          string         `json:"file_path"`
	FileSize          int64          `json:"file_size"`
	Format            string         `json:"format"`
	Bitrate           sql.NullInt64  `json:"bitrate"`
	ContentHash       sql.NullString `json:"content_hash"`
	TranscodingStatus sql.NullString `json:"transcoding_status"`
	OriginalFilename  sql.NullString `json:"original_filename"`
}

func (q *Queries) CreateTrackFile(ctx context.Context, arg CreateTrackFileParams) (TrackFile, error) {
	row := q.db.QueryRowContext(ctx, createTrackFile,
		arg.VersionID,
		arg.Quality,
		arg.FilePath,
		arg.FileSize,
		arg.Format,
		arg.Bitrate,
		arg.ContentHash,
		arg.TranscodingStatus,
		arg.OriginalFilename,
	)
	var i TrackFile
	err := row.Scan(
		&i.ID,
		&i.VersionID,
		&i.Quality,
		&i.FilePath,
		&i.FileSize,
		&i.Format,
		&i.Bitrate,
		&i.ContentHash,
		&i.TranscodingStatus,
		&i.CreatedAt,
		&i.Waveform,
		&i.OriginalFilename,
	)
	return i, err
}

const deleteTrackFile = `-- name: DeleteTrackFile :exec
DELETE FROM track_files
WHERE id = ?
`

func (q *Queries) DeleteTrackFile(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTrackFile, id)
	return err
}

const deleteTrackFilesByVersion = `-- name: DeleteTrackFilesByVersion :exec
DELETE FROM track_files
WHERE version_id = ?
`

func (q *Queries) DeleteTrackFilesByVersion(ctx context.Context, versionID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTrackFilesByVersion, versionID)
	return err
}

const findFileByContentHash = `-- name: FindFileByContentHash :one
SELECT id, version_id, quality, file_path, file_size, format, bitrate, content_hash, transcoding_status, created_at, waveform, original_filename FROM track_files
WHERE content_hash = ?
LIMIT 1
`

func (q *Queries) FindFileByContentHash(ctx context.Context, contentHash sql.NullString) (TrackFile, error) {
	row := q.db.QueryRowContext(ctx, findFileByContentHash, contentHash)
	var i TrackFile
	err := row.Scan(
		&i.ID,
		&i.VersionID,
		&i.Quality,
		&i.FilePath,
		&i.FileSize,
		&i.Format,
		&i.Bitrate,
		&i.ContentHash,
		&i.TranscodingStatus,
		&i.CreatedAt,
		&i.Waveform,
		&i.OriginalFilename,
	)
	return i, err
}

const getCompletedTrackFile = `-- name: GetCompletedTrackFile :one
SELECT id, version_id, quality, file_path, file_size, format, bitrate, content_hash, transcoding_status, created_at, waveform, original_filename FROM track_files
WHERE version_id = ? AND quality = ? AND transcoding_status = 'completed'
`

type GetCompletedTrackFileParams struct {
	VersionID int64  `json:"version_id"`
	Quality   string `json:"quality"`
}

func (q *Queries) GetCompletedTrackFile(ctx context.Context, arg GetCompletedTrackFileParams) (TrackFile, error) {
	row := q.db.QueryRowContext(ctx, getCompletedTrackFile, arg.VersionID, arg.Quality)
	var i TrackFile
	err := row.Scan(
		&i.ID,
		&i.VersionID,
		&i.Quality,
		&i.FilePath,
		&i.FileSize,
		&i.Format,
		&i.Bitrate,
		&i.ContentHash,
		&i.TranscodingStatus,
		&i.CreatedAt,
		&i.Waveform,
		&i.OriginalFilename,
	)
	return i, err
}

const getTrackFile = `-- name: GetTrackFile :one
SELECT id, version_id, quality, file_path, file_size, format, bitrate, content_hash, transcoding_status, created_at, waveform, original_filename FROM track_files
WHERE version_id = ? AND quality = ?
`

type GetTrackFileParams struct {
	VersionID int64  `json:"version_id"`
	Quality   string `json:"quality"`
}

func (q *Queries) GetTrackFile(ctx context.Context, arg GetTrackFileParams) (TrackFile, error) {
	row := q.db.QueryRowContext(ctx, getTrackFile, arg.VersionID, arg.Quality)
	var i TrackFile
	err := row.Scan(
		&i.ID,
		&i.VersionID,
		&i.Quality,
		&i.FilePath,
		&i.FileSize,
		&i.Format,
		&i.Bitrate,
		&i.ContentHash,
		&i.TranscodingStatus,
		&i.CreatedAt,
		&i.Waveform,
		&i.OriginalFilename,
	)
	return i, err
}

const getTrackFileByID = `-- name: GetTrackFileByID :one
SELECT id, version_id, quality, file_path, file_size, format, bitrate, content_hash, transcoding_status, created_at, waveform, original_filename FROM track_files
WHERE id = ?
`

func (q *Queries) GetTrackFileByID(ctx context.Context, id int64) (TrackFile, error) {
	row := q.db.QueryRowContext(ctx, getTrackFileByID, id)
	var i TrackFile
	err := row.Scan(
		&i.ID,
		&i.VersionID,
		&i.Quality,
		&i.FilePath,
		&i.FileSize,
		&i.Format,
		&i.Bitrate,
		&i.ContentHash,
		&i.TranscodingStatus,
		&i.CreatedAt,
		&i.Waveform,
		&i.OriginalFilename,
	)
	return i, err
}

const listAllTrackFiles = `-- name: ListAllTrackFiles :many
SELECT id, version_id, quality, file_path, file_size, format, bitrate, content_hash, transcoding_status, created_at, waveform, original_filename FROM track_files
ORDER BY id ASC
`

func (q *Queries) ListAllTrackFiles(ctx context.Context) ([]TrackFile, error) {
	rows, err := q.db.QueryContext(ctx, listAllTrackFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrackFile{}
	for rows.Next() {
		var i TrackFile
		if err := rows.Scan(
			&i.ID,
			&i.VersionID,
			&i.Quality,
			&i.FilePath,
			&i.FileSize,
			&i.Format,
			&i.Bitrate,
			&i.ContentHash,
			&i.TranscodingStatus,
			&i.CreatedAt,
			&i.Waveform,
			&i.OriginalFilename,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackFilesByVersion = `-- name: ListTrackFilesByVersion :many
SELECT id, version_id, quality, file_path, file_size, format, bitrate, content_hash, transcoding_status, created_at, waveform, original_filename FROM track_files
WHERE version_id = ?
`

func (q *Queries) ListTrackFilesByVersion(ctx context.Context, versionID int64) ([]TrackFile, error) {
	rows, err := q.db.QueryContext(ctx, listTrackFilesByVersion, versionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrackFile{}
	for rows.Next() {
		var i TrackFile
		if err := rows.Scan(
			&i.ID,
			&i.VersionID,
			&i.Quality,
			&i.FilePath,
			&i.FileSize,
			&i.Format,
			&i.Bitrate,
			&i.ContentHash,
			&i.TranscodingStatus,
			&i.CreatedAt,
			&i.Waveform,
			&i.OriginalFilename,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTrackFileSize = `-- name: UpdateTrackFileSize :exec
UPDATE track_files
SET file_size = ?
WHERE id = ?
`

type UpdateTrackFileSizeParams struct {
	FileSize int64 `json:"file_size"`
	ID       int64 `json:"id"`
}

func (q *Queries) UpdateTrackFileSize(ctx context.Context, arg UpdateTrackFileSizeParams) error {
	_, err := q.db.ExecContext(ctx, updateTrackFileSize, arg.FileSize, arg.ID)
	return err
}

const updateTranscodingStatus = `-- name: UpdateTranscodingStatus :exec
UPDATE track_files
SET transcoding_status = ?
WHERE id = ?
`

type UpdateTranscodingStatusParams struct {
	TranscodingStatus sql.NullString `json:"transcoding_status"`
	ID                int64          `json:"id"`
}

func (q *Queries) UpdateTranscodingStatus(ctx context.Context, arg UpdateTranscodingStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTranscodingStatus, arg.TranscodingStatus, arg.ID)
	return err
}

const updateWaveform = `-- name: UpdateWaveform :exec
UPDATE track_files
SET waveform = ?
WHERE id = ?
`

type UpdateWaveformParams struct {
	Waveform sql.NullString `json:"waveform"`
	ID       int64          `json:"id"`
}

func (q *Queries) UpdateWaveform(ctx context.Context, arg UpdateWaveformParams) error {
	_, err := q.db.ExecContext(ctx, updateWaveform, arg.Waveform, arg.ID)
	return err
}
